# Generated by Django 4.1.4 on 2022-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserProfile',
            field=models.CharField(default='https://github.com/hurricanemark', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employment',
            name='PhotoFileName',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
