# Generated by Django 4.1.4 on 2022-12-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJournal', '0002_users_userprofile_alter_employment_photofilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='Status',
            field=models.CharField(default=-8, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='UserEmail',
            field=models.EmailField(max_length=50),
        ),
    ]
