# Generated by Django 4.1.4 on 2022-12-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerJournal', '0003_employment_status_alter_users_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='Status',
            new_name='EmployeeStatus',
        ),
    ]
